import AppKit
import OSLog

private let log = Logger(
    subsystem: Bundle.main.bundleIdentifier ?? "Everest",
    category: "replacement.pasteboard"
)

extension NSPasteboard.PasteboardType {
    /// Markers from the nspasteboard.org convention, which every mainstream
    /// clipboard history app on macOS honours. They are ordinary pasteboard
    /// types with agreed names; there is no AppKit API for them.

    /// "Do not record this." The value is the moment the content stops being
    /// interesting, in ISO 8601.
    static let nsTransient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")

    /// "A program put this here, a person did not."
    static let nsAutoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}

/// Borrows the general pasteboard and gives it back.
///
/// Two paths in this app have to use the clipboard as a transport: the
/// synthetic copy that reads a selection out of an accessibility-hostile app,
/// and the synthetic paste that writes a rewrite into one. Both destroy
/// whatever the user had on the clipboard. This type is the apology.
///
/// The contract is:
///
/// 1. `snapshot()` before anything touches the pasteboard.
/// 2. Either `writeTransient(_:)` (we are the writer) or `expect(changeCount:)`
///    (the target app was the writer, after a synthetic copy).
/// 3. `restoreIfUnchanged()`, which puts the user's content back *only* if the
///    pasteboard is still exactly as our step 2 left it.
///
/// Step 3 is conditional on `changeCount` rather than on a timer. See
/// `AGENTS.md` in this directory for why a timer is not an acceptable
/// substitute.
@MainActor
final class PasteboardTransaction {

    /// One pasteboard item, flattened to every type it declared and the bytes
    /// behind each. Kept as an ordered array because pasteboard type order is
    /// preference order: the first type a reader recognises is the one it uses.
    /// A dictionary would silently reorder rich text below plain text.
    private struct SavedItem {
        var payloads: [(type: NSPasteboard.PasteboardType, data: Data)]
    }

    /// Ceiling on how much clipboard content is held in memory during a
    /// transaction. A pasted screenshot or a copied video frame can be hundreds
    /// of megabytes; duplicating that for a two second round trip is worse for
    /// the user than restoring their clipboard imperfectly.
    static let snapshotByteBudget = 16 * 1024 * 1024

    /// How long a transient marker claims the content stays interesting.
    private static let transientLifetime: TimeInterval = 10

    private let pasteboard: NSPasteboard
    private var saved: [SavedItem] = []
    private var didSnapshot = false
    private var expectedChangeCount: Int?

    /// How good the saved copy of the user's clipboard is.
    ///
    /// Three states, and they must stay three. An earlier version tracked this
    /// as "did we save anything", which conflated *the clipboard was empty*
    /// with *we could not afford to save it*, and the restore then cleared a
    /// clipboard it had never saved and reported success. A 40 MB image went in
    /// and an empty pasteboard came out, with no signal anywhere.
    enum Fidelity: Equatable {
        /// `snapshot()` has not run.
        case notTaken
        /// Every byte on the pasteboard is held. A restore puts it all back.
        /// This includes the genuinely empty clipboard, which restores to empty.
        case faithful
        /// The size budget dropped real bytes. A restore cannot be honest, so
        /// the transaction refuses to be used at all.
        case lossy
    }

    private(set) var fidelity: Fidelity = .notTaken

    /// Whether it is safe to disturb the pasteboard at all.
    ///
    /// **Check this before writing anything, including before posting a
    /// synthetic Command C that makes the target app write.** Once the
    /// pasteboard has been overwritten, the user's bytes are gone and no
    /// cleverness at the restore end can bring them back. The only place this
    /// can be handled is the front.
    var canBorrow: Bool { fidelity == .faithful }

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    // MARK: - Snapshot

    /// Copies every item and every declared type off the pasteboard.
    ///
    /// Reading only `.string` would be the easy version and it is wrong: a
    /// clipboard commonly carries the same content as RTF, HTML, PNG, a file
    /// URL, and plain text at once. Restoring only the plain text silently
    /// downgrades a copied table to a line of tab separated words, and the user
    /// has no way to know that Everest did it.
    ///
    /// Asking for the bytes of every type also forces lazy promise providers to
    /// deliver. That is a deliberate cost: a promise we did not resolve is a
    /// promise we cannot put back.
    /// Returns whether the pasteboard may now be borrowed. Callers must not
    /// ignore it: a false return means the user's clipboard cannot be put back,
    /// so it must not be disturbed.
    @discardableResult
    func snapshot() -> Bool {
        saved.removeAll()
        var lostBytes = false
        var remaining = Self.snapshotByteBudget

        for item in pasteboard.pasteboardItems ?? [] {
            var payloads: [(type: NSPasteboard.PasteboardType, data: Data)] = []
            for type in item.types {
                guard let data = item.data(forType: type) else {
                    // A derived flavour the owner cannot currently render, or a
                    // promise whose provider has gone away. Either way there
                    // are no bytes here to put back, so this is not a loss.
                    continue
                }
                guard data.count <= remaining else {
                    // Real bytes we are choosing not to hold. This is the only
                    // thing that makes a snapshot lossy.
                    lostBytes = true
                    continue
                }
                remaining -= data.count
                payloads.append((type, data))
            }
            if !payloads.isEmpty {
                saved.append(SavedItem(payloads: payloads))
            }
        }

        fidelity = lostBytes ? .lossy : .faithful
        didSnapshot = true

        if lostBytes {
            // Deliberately abandon what we did manage to hold. A partial
            // restore of a clipboard whose main payload we dropped would look
            // like a successful restore to every caller and to the user, while
            // actually having thrown their image away.
            saved.removeAll()
            log.info("clipboard exceeds the snapshot budget; refusing to borrow it")
        }

        log.debug(
            "snapshot: \(self.saved.count, privacy: .public) items, faithful=\(self.canBorrow, privacy: .public)"
        )
        return canBorrow
    }

    // MARK: - Writing

    /// Puts our own scratch content on the pasteboard and records the resulting
    /// change count as the one a restore is allowed to overwrite.
    ///
    /// The transient and auto-generated markers ride on the same item as the
    /// text so they show up in `NSPasteboard.types`, which is where clipboard
    /// managers look. Without them, every rewrite would leave a junk entry in
    /// the user's clipboard history.
    ///
    /// `org.nspasteboard.ConcealedType` is not set. It means "this is a
    /// password" and some managers surface a warning for it. The transient
    /// marker already prevents recording, so the stronger claim would be a
    /// misuse of the convention for no extra benefit.
    @discardableResult
    func writeTransient(_ string: String) -> Int {
        let item = NSPasteboardItem()
        item.setString(string, forType: .string)
        let stamp = Self.timestamp(offset: Self.transientLifetime)
        item.setString(stamp, forType: .nsTransient)
        item.setString(stamp, forType: .nsAutoGenerated)

        pasteboard.clearContents()
        pasteboard.writeObjects([item])

        let count = pasteboard.changeCount
        expectedChangeCount = count
        return count
    }

    /// Records a change count produced by somebody else, which is the case
    /// after a synthetic copy: the *target app* wrote the pasteboard, not us,
    /// so we adopt its change count as the value a restore may overwrite.
    func expect(changeCount: Int) {
        expectedChangeCount = changeCount
    }

    // MARK: - Restore

    /// Puts the user's clipboard back, if and only if nothing has touched the
    /// pasteboard since step 2.
    ///
    /// Returns true when a restore happened. False means either there was
    /// nothing to restore or, more importantly, that somebody else wrote the
    /// pasteboard in the meantime and their content was left alone.
    @discardableResult
    func restoreIfUnchanged() -> Bool {
        guard didSnapshot, let expected = expectedChangeCount else {
            discard()
            return false
        }

        // Backstop for the Critical bug this class had once. A lossy snapshot
        // should never have reached a write in the first place, because every
        // caller checks `canBorrow` first. If one ever forgets, refuse here and
        // leave the pasteboard exactly as it is. Clearing it would destroy the
        // very bytes we failed to save, which is strictly worse than leaving
        // our scratch text visible.
        guard fidelity == .faithful else {
            log.error("restore refused: snapshot was not faithful, leaving the pasteboard alone")
            discard()
            return false
        }

        guard pasteboard.changeCount == expected else {
            // Somebody copied something while we were working. It might be the
            // user pressing Command C in another window; it might be another
            // tool. Either way the current clipboard is newer than ours and
            // overwriting it would destroy content we never owned.
            log.debug("restore skipped: pasteboard changed underneath us")
            discard()
            return false
        }

        pasteboard.clearContents()
        defer { discard() }

        guard !saved.isEmpty else {
            // The clipboard really was empty before we started, because the
            // snapshot is faithful. Leaving it cleared is the correct restore.
            return true
        }

        let items = saved.map { entry -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for payload in entry.payloads {
                item.setData(payload.data, forType: payload.type)
            }
            return item
        }

        // The restored content is the user's own, so it is written plain. It is
        // not marked transient: a clipboard manager that missed the original
        // should be able to record this, and a duplicate history entry is a far
        // smaller harm than a manager showing our scratch text as the current
        // clipboard.
        let wrote = pasteboard.writeObjects(items)
        if !wrote { log.error("pasteboard restore failed") }
        return wrote
    }

    /// Gives up the saved content without restoring it. Used when we have
    /// decided on purpose to leave our own text on the clipboard, which is what
    /// a `.copiedOnly` outcome means.
    func abandon() {
        discard()
    }

    /// Drops the held copy promptly. Worth doing rather than waiting for
    /// deallocation, because `saved` can be up to the byte budget of the user's
    /// clipboard and there is no reason to keep an image alive after the
    /// transaction is over.
    private func discard() {
        saved.removeAll()
        didSnapshot = false
        expectedChangeCount = nil
        fidelity = .notTaken
    }

    // MARK: - Durable write

    /// Writes text the user is expected to paste themselves.
    ///
    /// The opposite of `writeTransient`: no markers, because this content is
    /// meant to survive and to be recorded by a clipboard manager. Every
    /// `.copiedOnly` outcome goes through here, so the phrase "copied only" is
    /// always literally true.
    static func writeDurable(_ string: String, to pasteboard: NSPasteboard = .general) {
        pasteboard.clearContents()
        pasteboard.setString(string, forType: .string)
    }

    private static func timestamp(offset: TimeInterval) -> String {
        let formatter = ISO8601DateFormatter()
        formatter.timeZone = TimeZone(secondsFromGMT: 0)
        return formatter.string(from: Date().addingTimeInterval(offset))
    }
}
